#!/bin/bash
#====================================================================
# BASH Functions (for Systemd support)
#--------------------------------------------------------------------
# Some are mine, some are others. Thanks to those who contributed
#====================================================================

function service(){
  service="$1"
  action="$2"
  shift 2
  echo "Rewriting to systemctl $action $service $@"
  return systemctl $action $service $@
}
