#!/bin/bash
#====================================================================
# BASH Functions (for SSH support)
#--------------------------------------------------------------------
# Some are mine, some are others. Thanks to those who contributed
#====================================================================

ssh-hostkey-clear(){
	line="$1"
	[ -z $line ] && read -p "What line is the bad key on? " line
	sed -i "${line}d" ~/.ssh/known_hosts
}
