#!/bin/bash
#====================================================================
# BASH Alias (command wrappers)
#--------------------------------------------------------------------
# Simple command wrappers
#====================================================================

command_exists watch && alias watch='watch --color --errexit'
