#!/bin/bash
#====================================================================
# BASH Alias
#--------------------------------------------------------------------
# Some are mine, some are others. Thanks to those who contributed
#====================================================================

#-------------------------------------------------------------
# Basic, high-level aliases
#-------------------------------------------------------------
alias which='type -a'
alias df='df -h'
alias reset='cd ~; clear'
alias r='reset'
alias h='cd ~'
alias c='clear'
alias ..='cd ..'
alias ...='cd ../..'

#--------------------------------------------------------------------
# The 'ls' family (this assumes you use a recent GNU ls).
#--------------------------------------------------------------------
# alias ls='ls --color=auto' # Enable color support
alias lx='ls -lhXB'        # Sort by extension.
alias lk='ls -lhSr'        # Sort by size, biggest last.
alias lt='ls -lhtr'        # Sort by date, most recent last.
alias lc='ls -lhtcr'       # Sort by/show change time,most recent last.
alias lu='ls -lhtur'       # Sort by/show access time,most recent last.

# The ubiquitous 'll': directories first, with alphanumeric sorting:
alias ll="ls -lh"
alias lm='ll | more'   #  Pipe through 'more'
alias lr='ll -R'       #  Recursive ls.
alias la='ll -A'       #  Show hidden files.
alias tree='tree -Csh' #  Nice alternative to 'recursive ls' ...

#-------------------------------------------------------------
# Personal aliases
#-------------------------------------------------------------
alias hosts='sudo nano /etc/hosts'
alias path='echo -e ${PATH//:/\\n}' # Pretty-print of some PATH variables

#-------------------------------------------------------------
# Personal typo fixes
#-------------------------------------------------------------
alias cd..='cd ..'
#alias ;;='ll'
alias l='ll'

load_dot_file "myShell/aliases.d/cmd-wrappers"

#-------------------------------------------------------------
# Dynamicly loaded alias files
#-------------------------------------------------------------
[ -f /etc/arch-release ] && load_dot_file "myShell/aliases.d/arch-linux"
command_exists apt-get   && load_dot_file "myShell/aliases.d/apt"
command_exists yum       && load_dot_file "myShell/aliases.d/yum"
[ -d ~/.homestead ]      && load_dot_file "myShell/aliases.d/homestead"
[ `uname` == "Darwin" ]  && load_dot_file "myShell/aliases.d/darwin"
