#!/bin/bash
#====================================================================
# BASH Functions
#--------------------------------------------------------------------
# Some are mine, some are others. Thanks to those who contributed
#====================================================================

#-------------------------------------------------------------
# General purpose functions (scripting support)
#-------------------------------------------------------------
load_dot_file "myShell/func.d/scripting"

#-------------------------------------------------------------
# General purpose macros
#-------------------------------------------------------------
load_dot_file "myShell/func.d/macros"

#-------------------------------------------------------------
# Global tools
#-------------------------------------------------------------
load_dot_file "myShell/func.d/fs"
load_dot_file "myShell/func.d/network"
load_dot_file "myShell/func.d/ssh"

#-------------------------------------------------------------
# Arch Tools
#-------------------------------------------------------------
command_exists pacman && load_dot_file "myShell/func.d/arch-linux"

#-------------------------------------------------------------
# Debian Tools
#-------------------------------------------------------------
[ -f /etc/debian-release ] && load_dot_file "myShell/func.d/debian"

#-------------------------------------------------------------
# Redhat Tools
#-------------------------------------------------------------
[ -f /etc/redhat-release ] && load_dot_file "myShell/func.d/rhel"

#-------------------------------------------------------------
# Systemd Tools
#-------------------------------------------------------------
command_exists systemctl && load_dot_file "myShell/func.d/systemd"

#-------------------------------------------------------------
# Docker Tools
#-------------------------------------------------------------
command_exists docker && load_dot_file "myShell/func.d/docker"
