#!/bin/bash
#====================================================================
# BASH Functions
#--------------------------------------------------------------------
# Some are mine, some are others. Thanks to those who contributed
#====================================================================

#-------------------------------------------------------------
# General purpose functions (scripting support)
#-------------------------------------------------------------
load_dot_file "myShell/func.d/scripting"

#-------------------------------------------------------------
# General purpose macros
#-------------------------------------------------------------
load_dot_file "myShell/func.d/macros"

#-------------------------------------------------------------
# Global tools
#-------------------------------------------------------------
load_dot_file "myShell/func.d/fs"
load_dot_file "myShell/func.d/network"
load_dot_file "myShell/func.d/ssh"
load_dot_file "myShell/func.d/projects"

#-------------------------------------------------------------
# Livestreamer (http://docs.livestreamer.io)
#-------------------------------------------------------------
command_exists livestreamer && load_dot_file "myShell/func.d/livestreamer"

#-------------------------------------------------------------
# Arch Tools
#-------------------------------------------------------------
command_exists pacman && load_dot_file "myShell/func.d/arch-linux"

#-------------------------------------------------------------
# Debian Tools
#-------------------------------------------------------------
[ -f /etc/debian-release ] && load_dot_file "myShell/func.d/debian"

#-------------------------------------------------------------
# Redhat Tools
#-------------------------------------------------------------
[ -f /etc/redhat-release ] && load_dot_file "myShell/func.d/rhel"

#-------------------------------------------------------------
# Systemd Tools
#-------------------------------------------------------------
command_exists systemctl && load_dot_file "myShell/func.d/systemd"

#-------------------------------------------------------------
# Docker Tools
#-------------------------------------------------------------
command_exists docker && load_dot_file "myShell/func.d/docker"

#-------------------------------------------------------------
# LDAP Tools
#-------------------------------------------------------------
command_exists ldapsearch && load_dot_file "myShell/func.d/ldap"

#-------------------------------------------------------------
# Laravel Homestead (https://laravel.com/docs/master/homestead)
#-------------------------------------------------------------
export HOMESTEAD_DIR="$HOME/.homestead"
[ -d "$HOMESTEAD_DIR" ] && load_dot_file "myShell/func.d/homestead"
