#!/usr/bin/env zsh

# Local bin (if it exists)
[ -d "$HOME/bin" ]  && PATH="$HOME/bin:$PATH"
[ -d "$HOME/.bin" ] && PATH="$HOME/.bin:$PATH"

# Synced bin (via Dropbox)
# [ -d "$HOME/Dropbox/sync/bin" ] && PATH="$HOME/Dropbox/sync/bin:$PATH"

# PHP Composer bin (if it exists)
[ -d "$HOME/.composer/vendor/bin" ] && PATH="$HOME/.composer/vendor/bin:$PATH"
[ -d "$HOME/.config/composer/vendor/bin" ] && PATH="$HOME/.config/composer/vendor/bin:$PATH"


# RVM bin (if it exists)
[ -d "$HOME/.rvm/bin" ] && PATH="$HOME/.rvm/bin:$PATH"

# Android SDK bin (if it exists)
#[ -d "$HOME/opt/androidDevKit/current/sdk/tools" ] && PATH="$PATH:$HOME/opt/androidDevKit/current/sdk/tools"
#[ -d "$HOME/opt/androidDevKit/current/sdk/platform-tools" ] && PATH="$PATH:$HOME/opt/androidDevKit/current/sdk/platform-tools"

# Load RVM



# Add . to the start of PATH for any local executables (Keep at the end of the file to put it at the start of PATH)
export PATH=".:$PATH"
