#!/bin/bash
#====================================================================
# BASH Functions
#--------------------------------------------------------------------
# Some are mine, some are others. Thanks to those who contributed
#====================================================================

#-------------------------------------------------------------
# General purpose functions (scripting support)
#-------------------------------------------------------------
source_file "$ZDOTDIR/extras/fn.d/scripting"

#-------------------------------------------------------------
# General purpose macros
#-------------------------------------------------------------
source_file "$ZDOTDIR/extras/fn.d/macros"

#-------------------------------------------------------------
# Global tools
#-------------------------------------------------------------
source_file "$ZDOTDIR/extras/fn.d/fs"
source_file "$ZDOTDIR/extras/fn.d/network"
source_file "$ZDOTDIR/extras/fn.d/ssh"

#-------------------------------------------------------------
# Arch Tools
#-------------------------------------------------------------
#source_file "$ZDOTDIR/extras/fn.d/arch-linux"

#-------------------------------------------------------------
# Debian Tools
#-------------------------------------------------------------
# [ -f /etc/debian-release ] && source_file "$ZDOTDIR/extras/fn.d/debian"

#-------------------------------------------------------------
# Redhat Tools
#-------------------------------------------------------------
# [ -f /etc/redhat-release ] && source_file "$ZDOTDIR/extras/fn.d/rhel"

#-------------------------------------------------------------
# Systemd Tools
#-------------------------------------------------------------
# command_exists systemctl && source_file "$ZDOTDIR/extras/fn.d/systemd"

#-------------------------------------------------------------
# Docker Tools
#-------------------------------------------------------------
# command_exists docker && source_file "$ZDOTDIR/extras/fn.d/docker"
