#!/bin/bash
#====================================================================
# BASH Alias
#--------------------------------------------------------------------
# Some are mine, some are others. Thanks to those who contributed
#====================================================================

#-------------------------------------------------------------
# Basic, high-level aliases
#-------------------------------------------------------------
alias which='type -a'
alias df='df -kTh' # Human-readable filesystem filesizes
alias reset='cd ~; clear'
alias r='reset'
alias h='cd ~'
alias c='clear'
alias ..='cd ..'
alias ...='cd ../..'

#-------------------------------------------------------------
# Enable color support
#-------------------------------------------------------------
#type dircolors >/dev/null 2>&1 && colorSupport="--color=auto" || colorSupport=""
#alias ls="ls $colorSupport"
#alias dir="dir $colorSupport"
#alias vdir="vdir $colorSupport"
#alias grep="grep $colorSupport"
#alias fgrep="fgrep $colorSupport"
#alias egrep="egrep $colorSupport"

#--------------------------------------------------------------------
# The 'ls' family (this assumes you use a recent GNU ls).
#--------------------------------------------------------------------
alias ls='ls -h'     # Human-readable filesizes
alias lx='ls -lXB'   # Sort by extension.
alias lk='ls -lSr'   # Sort by size, biggest last.
alias lt='ls -ltr'   # Sort by date, most recent last.
alias lc='ls -ltcr'  # Sort by/show change time,most recent last.
alias lu='ls -ltur'  # Sort by/show access time,most recent last.

# The ubiquitous 'll': directories first, with alphanumeric sorting:
alias ll="ls -lvh"
alias lm='ll | more'   #  Pipe through 'more'
alias lr='ll -R'       #  Recursive ls.
alias la='ll -A'       #  Show hidden files.
alias tree='tree -Csh' #  Nice alternative to 'recursive ls' ...

#-------------------------------------------------------------
# Personal aliases
#-------------------------------------------------------------
alias hosts='sudo nano /etc/hosts'
alias path='echo -e ${PATH//:/\\n}' # Pretty-print of some PATH variables

#-------------------------------------------------------------
# Personal typo fixes
#-------------------------------------------------------------
alias cd..='cd ..'
alias l='ll'

#-------------------------------------------------------------
# Dynamicly loaded alias files
#-------------------------------------------------------------
[ -f /etc/arch-release ] && sourceFile "$_DOT_FILES/extras/aliases.d/arch-linux"
command_exists apt-get   && sourceFile "$_DOT_FILES/extras/aliases.d/apt"
command_exists yum       && sourceFile "$_DOT_FILES/extras/aliases.d/yum"
[ -d ~/.homestead ]      && sourceFile "$_DOT_FILES/extras/aliases.d/homestead"
