#!/bin/bash
#====================================================================
# BASH Functions
#--------------------------------------------------------------------
# Some are mine, some are others. Thanks to those who contributed
#====================================================================
echo $BASH_SOURCE
#-------------------------------------------------------------
# General purpose functions (scripting support)
#-------------------------------------------------------------
sourceFile "$_DOT_FILES/extras/fn.d/scripting"

#-------------------------------------------------------------
# General purpose macros
#-------------------------------------------------------------
sourceFile "$_DOT_FILES/extras/fn.d/macros"

#-------------------------------------------------------------
# Global tools
#-------------------------------------------------------------
sourceFile "$_DOT_FILES/extras/fn.d/fs"
sourceFile "$_DOT_FILES/extras/fn.d/network"
sourceFile "$_DOT_FILES/extras/fn.d/ssh"

#-------------------------------------------------------------
# Arch Tools
#-------------------------------------------------------------
#sourceFile "$_DOT_FILES/extras/fn.d/arch-linux"

#-------------------------------------------------------------
# Debian Tools
#-------------------------------------------------------------
[ -f /etc/debian-release ] && sourceFile "$_DOT_FILES/extras/fn.d/debian"

#-------------------------------------------------------------
# Redhat Tools
#-------------------------------------------------------------
[ -f /etc/redhat-release ] && sourceFile "$_DOT_FILES/extras/fn.d/rhel"

#-------------------------------------------------------------
# Systemd Tools
#-------------------------------------------------------------
command_exists systemctl && sourceFile "$_DOT_FILES/extras/fn.d/systemd"

#-------------------------------------------------------------
# Docker Tools
#-------------------------------------------------------------
command_exists docker && sourceFile "$_DOT_FILES/extras/fn.d/docker"
